### PR TITLE
Update chapter23.md

### PR DESCRIPTION
**Pull request by rdthree**
added an update function to Box, I couldn't get the collision detection to work with tempStrength without this

### CODE REVIEW

**Comment by Sheepolution** [comment]
If function `Box:update(dt)` doesn't exist, it will use its super class' function. So `Entity:update(dt)`.
Are you sure this change makes a difference in whether it works?

**Comment by rdthree** [comment]
it could be me, I'm a learner so it's very likely I did something wrong.  Here is my code, albeit from chapter 24:

https://github.com/originalsurfmex/sheepolution_collision_meister/tree/master

thanks for even responding to this pull request in addition to putting up those tutorials.  much appreciated!

**Comment by rafauke** [comment]
Hello @originalsurfmex,

I have downloaded your example and everything seems to work ok. Would you be so kind and explain what exactly doesn't work as expected or what are you trying to achieve in your game? :)

**Comment by rdthree** [comment]
yeah the box wouldn't move as expected unless I added that code.  not sure why.  I probably won't be able to re-investigate this for a few months.  If you like I can close this since it doesn't seem to be an issue for anyone else.

**Pull request closed without merging**
